### ISSUE TITLE
!arturdebil not working

### ISSUE THREAD

**Issue by Kojfer13** [Barsik008/PossumBot#101]
Arturdebil does not work.
Bot has admin permissions

Cmd output:
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at C:\Users\Maciek\Desktop\PossumBot-master\node_modules\discord.js\src\managers\GuildMemberManager.js:317:16
    at Timeout._onTimeout (C:\Users\Maciek\Desktop\PossumBot-master\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at C:\Users\Maciek\Desktop\PossumBot-master\node_modules\discord.js\src\managers\GuildMemberManager.js:317:16
    at Timeout._onTimeout (C:\Users\Maciek\Desktop\PossumBot-master\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by Barsik008** [comment]
@Kojfer13 do you have intents enabled?

**Comment by YilmazBrkT** [comment]
@Barsik008 how do we enable intents?

**Comment by Barsik008** [comment]
@YilmazBrkT read the guide
