### ISSUE TITLE
SyntaxError: Unexpected number

### ISSUE THREAD

**Issue by Popcornettay** [Barsik008/PossumBot#128]
```
C:\Users\'user'\Desktop\PossumBot-master>node Startbot.bat
C:\Users\'user'\Desktop\PossumBot-master\Startbot.bat:1
WScript.Sleep 3000
              ^^^^

SyntaxError: Unexpected number
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1001:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1049:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

```

I can't resolve it by myself. Can you help me ?

**Comment by Popcornettay** [comment]
It was just because I've changed the prefix for the commands.
