### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by C0okie2** [Barsik008/PossumBot#138]
HTTPError [FetchError]: request to https://discord.com/api/v7/gateway/bot failed, reason: unable to get local issuer certificate
    at RequestHandler.execute (C:\Users\teacher\Downloads\PossumBot-master\PossumBot-master\node_modules\discord.js\src\rest\RequestHandler.js:93:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\teacher\Downloads\PossumBot-master\PossumBot-master\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async WebSocketManager.connect (C:\Users\teacher\Downloads\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:138:9)
    at async Client.login (C:\Users\teacher\Downloads\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\Client.js:222:7) {
  code: 500,
  method: 'get',
  path: '/gateway/bot'

**Comment by C0okie2** [comment]
When I put node bot.js, this pops up
