### ISSUE TITLE
Error with command `node bot.js`

### ISSUE THREAD

**Issue by fluid46** [Barsik008/PossumBot#15]

**Comment by fluid46** [comment]
Loading Commands...
(node:28280) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (D:\Desktop\PossumBot-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:418:26)
    at WebSocketConnection.emit (events.js:311:20)
    at WebSocketConnection.onClose (D:\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (D:\Desktop\PossumBot-master\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:311:20)
    at D:\Desktop\PossumBot-master\node_modules\ws\lib\websocket.js:220:12
    at Receiver.cleanup (D:\Desktop\PossumBot-master\node_modules\ws\lib\receiver.js:535:15)
    at WebSocket.finalize (D:\Desktop\PossumBot-master\node_modules\ws\lib\websocket.js:206:20)
    at TLSSocket.emit (events.js:323:22)
(node:28280) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:28280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Barsik008** [comment]
wrong token in botsettings.js
