### ISSUE TITLE
The bot is not working

### ISSUE THREAD

**Issue by basketballsmash** [Barsik008/PossumBot#31]
I started the bot, used the command, and seems to be not working, just deleting what i type

i type: !arturdebil
it just deletes what i typed

**Comment by basketballsmash** [comment]
it gives me this error

TypeError: Cannot read property 'members' of null
    at Object.module.exports.run (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\commands\arturdebil.js:7:23)
    at Client.<anonymous> (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\bot.js:70:7)
    at Client.emit (events.js:315:20)
    at MessageCreateHandler.handle (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver._receiver.onmessage (C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master\node_modules\ws\lib\websocket.js:137:47)

note that i have my bot in C:\Users\shuji\Desktop\hackbot\PossumBot-master\PossumBot-master

**Comment by shinchan-pb-xi** [comment]
Use users instead of members... it may work

**Comment by LeManock** [comment]
Members => users

**Comment by Barsik008** [comment]
@basketballsmash Make sure the bot has admin perms.
