### ISSUE TITLE
error on step 9

### ISSUE THREAD

**Issue by Wagons2ElectricBoogaloo** [Barsik008/PossumBot#32]
error on step 9
Loading Commands...
(node:16916) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
at WebSocketConnection. (C:\Users\Zak\Desktop\PossumBot-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
at Object.onceWrapper (events.js:422:26)
at WebSocketConnection.emit (events.js:315:20)
at WebSocketConnection.onClose (C:\Users\Zak\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
at WebSocket.onClose (C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\event-target.js:124:16)
at WebSocket.emit (events.js:315:20)
at C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\websocket.js:220:12
at Receiver.cleanup (C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\receiver.js:535:15)
at WebSocket.finalize (C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\websocket.js:206:20)
at TLSSocket.emit (events.js:327:22)
(node:16916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Wagons2ElectricBoogaloo** [comment]
update: i figured it out and im now getting an error

**Comment by Wagons2ElectricBoogaloo** [comment]
Loading Commands...
(node:16916) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\Zak\Desktop\PossumBot-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (C:\Users\Zak\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\websocket.js:220:12
    at Receiver.cleanup (C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\receiver.js:535:15)
    at WebSocket.finalize (C:\Users\Zak\Desktop\PossumBot-master\node_modules\ws\lib\websocket.js:206:20)
    at TLSSocket.emit (events.js:327:22)
(node:16916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Barsik008** [comment]
change the token value in botsettings.json

**Comment by Barsik008** [comment]
@Wagons2ElectricBoogaloo change the token value in botsettings.json

**Comment by Wagons2ElectricBoogaloo** [comment]
What do I change it to tho

**Comment by Barsik008** [comment]
@Wagons2ElectricBoogaloo Ask the admin of the server nicely.
