### ISSUE TITLE
admin isnt working.

### ISSUE THREAD

**Issue by WarySwary** [Barsik008/PossumBot#34]
when I run !meadmin, nothing happens.
Error Message: TypeError: message.guild.createRole is not a function
    at Client.bot.on (/app/bot.js:27:29)
    at Client.emit (events.js:189:13)
    at MessageCreateAction.handle (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/discord.js/12.2.0/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/ws/7.3.0/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/rbd/pnpm-volume/e7d78f68-8957-45ea-b60b-aaa82632026f/node_modules/.registry.npmjs.org/ws/7.3.0/node_modules/ws/lib/websocket.js:800:20)

**Comment by Barsik008** [comment]
!meadmin isnt a command. Try !myakish
