### ISSUE TITLE
Ban command is not working.

### ISSUE THREAD

**Issue by SniperXKiller** [Barsik008/PossumBot#52]
Hi, SXK here,
I can't seem to get the ban command to work. And yes, I checked my grammar. This is the ONLY command that doesn't work.

**Comment by SniperXKiller** [comment]
TypeError: message.guild.members.filter is not a function
    at Object.module.exports.run (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\commands\arturdebil.js:7:31)
    at Client.<anonymous> (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\bot.js:64:7)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Evan Mark\PossumBot-master\PossumBot-master\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)

**Comment by Barsik008** [comment]
@SniperXKiller im in the process of fixing this.

**Comment by prateekpy** [comment]
@Barsik008 Please Fix this fast :(

**Comment by SterBen-Dev** [comment]
yeah fix it fast pls

**Comment by Mariic33** [comment]
How can I update the arturdebil command?

**Comment by Sandeep1344** [comment]
Ban commnad not working plz fix

**Comment by WinnieV2** [comment]
Has this been fixed yet ?
