### ISSUE TITLE
ARTURDEBIL DOESNT WORK

### ISSUE THREAD

**Issue by baby-Mario** [Barsik008/PossumBot#79]
TypeError: message.guild.members.filter is not a function
    at Object.module.exports.run (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\commands\arturdebil.js:7:31)
    at Client.<anonymous> (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\bot.js:64:7)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Gabriel Enchill\Desktop\PossumBot-master\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)

**Comment by dragonDScript** [comment]
https://stackoverflow.com/help/how-to-ask can help.

**Comment by notSalt** [comment]
Have you checked if you enabled Intents for server members?

**Comment by Barsik008** [comment]
@baby-Mario do other commands work?

**Comment by Necromonster** [comment]
non of the cmds work, lol

**Comment by dragonDScript** [comment]
console.dir(message) please
